name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.x'
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install twine
        python -m pip install build
        python -m build
        python -m twine upload dist/*